language: go

sudo: false

go:
  - 1.2.x
  - 1.3.x
  - 1.4.2
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get github.com/urfave/cli
  - go get github.com/stretchr/testify/assert

script:
  - go test -v ./...
